 var a = 10;
 var b = 20;
 var c = 30;
 var d = 40;
 var e = 50;
 var add = a+b+c+d+e;
 console.log(add);
 var subtract = add-40;
 console.log(subtract);
 var multiply = subtract*30;
 console.log(multiply); 
